"""alert_rule_operator

Revision ID: 488b28ac7625
Revises: 113115232ed4
Create Date: 2026-08-14 05:36:47.301516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488b28ac7625'
down_revision: Union[str, Sequence[str], None] = '113115232ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('operator', sa.String(length=4), server_default='>', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_column('alert_rules', 'operator')
    # ### end Alembic commands ###
